name: Afternoon Trade Workflow

on:
  workflow_dispatch
  # schedule:
  #   - cron: '55 17 * * 1-6'  # Run daily at midnight (adjust as needed)

env:
  GH_TOKEN=${{ secrets.REPO_PAT }}
  TICKER=${{ env.TICKER }}
  SCHWAB_REFRESH_TOKEN=${{ secrets.SCHWAB_REFRESH_TOKEN }}
  SCHWAB_BASE_URL=${{ env.SCHWAB_BASE_URL }}
  SCHWAB_ACCT_NUMBER=${{ secrets.SCHWAB_ACCT_NUMBER }}
  SCHWAB_APP_KEY=${{ secrets.SCHWAB_APP_KEY }}
  SCHWAB_APP_SECRET=${{ secrets.SCHWAB_APP_SECRET }}

jobs:
  trading:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Retrieve secrets
        run: |
          GH_TOKEN=${{ secrets.REPO_PAT }}


      - name: Run trading script
        run: |
          python afternoon_trade.py

      - name: Commit and push changes
        run: |
          git config user.email "mschilling52019@gmail.com"
          git config user.name "MattBot"
          git add trading_data.csv
          git add logs/app.log
          git commit -m "Update trading data"
          git push origin main