name: Morning Trade Workflow

on:
  schedule:
    - cron: '30 13 * * 1-6'  # Run daily at midnight (adjust as needed)

jobs:
  trading:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Retrieve secrets
        run: |
          GH_TOKEN=${{ secrets.REPO_PAT }}
          Ticker=${{ env.Ticker }}
          Schwab_refresh_token=${{ secrets.Schwab_refresh_token }}
          Schwab_base_url=${{ env.Schwab_base_url }}
          Schwab_acct_number=${{ secrets.Schwab_acct_number }}
          Schwab_app_key=${{ secrets.Schwab_app_key }}
          Schwab_app_secret=${{ secrets.Schwab_app_secret }}

      - name: Run trading script
        run: |
          python morning_trade.py

      - name: Commit and push changes
        run: |
          git config user.email "mschilling52019@gmail.com"
          git config user.name "MattBot"
          git add trading_data.csv
          git add logs/app.log
          git commit -m "Update trading data"
          git push origin main